[package]
name = "tipro-to-midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.2"
evdev = "0.12.1"
hidapi = "2.4.1"
log = "0.4.20"
midir = "0.9.1"
